"use client";

import { fetchWithAuth } from "@/lib/client-fetch";
import { useCSVExport, exportToCSV, generateExportFilename } from "@/lib/csv";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  PageContainer,
  PageHeader,
  PageContent,
  LoadingSpinner,
  ErrorState,
  EmptyState,
} from "@/components/shared";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  BarChart3,
  RefreshCw,
  Download,
  Printer,
  ArrowLeftRight,
  Bookmark,
  Clock,
  Loader2,
} from "lucide-react";

import { escapeHtml, printHtml } from "@/lib/print";

interface DashboardStats {
  checkouts_today: number | null;
  checkins_today: number | null;
  active_holds: number | null;
  overdue_items: number | null;
  fines_collected_today: number | null;
  new_patrons_today: number | null;
}

interface HoldsStats {
  available: number;
  pending: number;
  in_transit: number;
  total: number;
}

function downloadTextFile(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function buildPrintSummaryHtml(params: {
  orgId: number;
  stats: DashboardStats;
  holds: HoldsStats;
}) {
  const now = new Date();

  const row = (k: string, v: string | number) =>
    `<tr><td class="k">${escapeHtml(k)}</td><td class="v right">${escapeHtml(v)}</td></tr>`;

  return [
    '<div class="box">',
    '<div class="brand">StacksOS</div>',
    '<h1 style="margin-top:4px">Daily Summary</h1>',
    `<div class="muted">${escapeHtml(now.toLocaleString())} · Org ${escapeHtml(params.orgId)}</div>`,
    "</div>",
    "<h2>Circulation</h2>",
    "<table>",
    "<thead><tr><th>Metric</th><th class=\"right\">Value</th></tr></thead>",
    "<tbody>",
    row("Checkouts (today)", params.stats.checkouts_today ?? "—"),
    row("Checkins (today)", params.stats.checkins_today ?? "—"),
    row("Active holds", params.stats.active_holds ?? "—"),
    row("Overdue items", params.stats.overdue_items ?? "—"),
    "</tbody>",
    "</table>",
    "<h2>Holds</h2>",
    "<table>",
    "<thead><tr><th>Status</th><th class=\"right\">Count</th></tr></thead>",
    "<tbody>",
    row("Ready / Available", params.holds.available),
    row("Pending", params.holds.pending),
    row("In transit", params.holds.in_transit),
    row("Total", params.holds.total),
    "</tbody>",
    "</table>",
    '<div class="muted" style="margin-top:16px">Generated by StacksOS (Evergreen-backed).</div>',
  ].join("\n");
}

export default function ReportsPage() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [holds, setHolds] = useState<HoldsStats | null>(null);
  const [orgId, setOrgId] = useState(1);
  const [lastRefresh, setLastRefresh] = useState<Date>(new Date());

  // CSV export hook for managing loading states
  const { exportData, isExporting } = useCSVExport();

  useEffect(() => {
    if (typeof window === "undefined") return;
    const raw = localStorage.getItem("stacksos_workstation_org");
    const parsed = raw ? parseInt(raw, 10) : NaN;
    if (Number.isFinite(parsed)) setOrgId(parsed);
  }, []);

  const loadAll = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const [statsRes, holdsRes] = await Promise.all([
        fetchWithAuth(`/api/evergreen/reports?action=dashboard&org=${orgId}`),
        fetchWithAuth(`/api/evergreen/reports?action=holds&org=${orgId}`),
      ]);

      const statsJson = await statsRes.json();
      const holdsJson = await holdsRes.json();

      if (!statsRes.ok || statsJson.ok === false) {
        throw new Error(statsJson.error || "Failed to load dashboard stats");
      }
      if (!holdsRes.ok || holdsJson.ok === false) {
        throw new Error(holdsJson.error || "Failed to load holds stats");
      }

      setStats(statsJson.stats || null);
      setHolds(holdsJson.holds || null);
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      setError(e);
    } finally {
      setLoading(false);
      setLastRefresh(new Date());
    }
  }, [orgId]);

  useEffect(() => {
    void loadAll();
  }, [loadAll]);

  const statCards = useMemo(() => {
    if (!stats) return [];
    return [
      {
        label: "Checkouts",
        value: stats.checkouts_today,
        icon: ArrowLeftRight,
        tone: "bg-emerald-500/10 text-emerald-600",
      },
      {
        label: "Checkins",
        value: stats.checkins_today,
        icon: ArrowLeftRight,
        tone: "bg-blue-500/10 text-blue-600",
      },
      {
        label: "Active holds",
        value: stats.active_holds,
        icon: Bookmark,
        tone: "bg-amber-500/10 text-amber-600",
      },
      {
        label: "Overdue",
        value: stats.overdue_items,
        icon: Clock,
        tone: "bg-rose-500/10 text-rose-600",
      },
    ];
  }, [stats]);

  // Export all reports data as a single CSV
  const handleDownloadFullReport = useCallback(async () => {
    if (!stats || !holds) return;

    const data = [{
      date: new Date().toISOString().split("T")[0],
      org_id: orgId,
      checkouts_today: stats.checkouts_today ?? "",
      checkins_today: stats.checkins_today ?? "",
      active_holds: stats.active_holds ?? "",
      overdue_items: stats.overdue_items ?? "",
      fines_collected_today: stats.fines_collected_today ?? "",
      new_patrons_today: stats.new_patrons_today ?? "",
      holds_available: holds.available,
      holds_pending: holds.pending,
      holds_in_transit: holds.in_transit,
      holds_total: holds.total,
    }];

    await exportData(
      generateExportFilename(`stacksos-full-report-org${orgId}`),
      data,
      {
        headers: {
          date: "Date",
          org_id: "Organization ID",
          checkouts_today: "Checkouts Today",
          checkins_today: "Checkins Today",
          active_holds: "Active Holds",
          overdue_items: "Overdue Items",
          fines_collected_today: "Fines Collected Today",
          new_patrons_today: "New Patrons Today",
          holds_available: "Holds Available",
          holds_pending: "Holds Pending",
          holds_in_transit: "Holds In Transit",
          holds_total: "Holds Total",
        },
      }
    );
  }, [stats, holds, orgId, exportData]);

  // Export circulation statistics only
  const handleDownloadCirculationStats = useCallback(async () => {
    if (!stats) return;

    const data = [{
      date: new Date().toISOString().split("T")[0],
      org_id: orgId,
      checkouts_today: stats.checkouts_today ?? 0,
      checkins_today: stats.checkins_today ?? 0,
      active_holds: stats.active_holds ?? 0,
      overdue_items: stats.overdue_items ?? 0,
      fines_collected_today: stats.fines_collected_today ?? 0,
      new_patrons_today: stats.new_patrons_today ?? 0,
    }];

    await exportData(
      generateExportFilename(`stacksos-circulation-org${orgId}`),
      data,
      {
        headers: {
          date: "Date",
          org_id: "Organization ID",
          checkouts_today: "Checkouts Today",
          checkins_today: "Checkins Today",
          active_holds: "Active Holds",
          overdue_items: "Overdue Items",
          fines_collected_today: "Fines Collected Today",
          new_patrons_today: "New Patrons Today",
        },
      }
    );
  }, [stats, orgId, exportData]);

  // Export holds statistics only
  const handleDownloadHoldsStats = useCallback(async () => {
    if (!holds) return;

    const data = [
      {
        status: "Available",
        count: holds.available,
        percentage: ((holds.available / holds.total) * 100).toFixed(1),
      },
      {
        status: "Pending",
        count: holds.pending,
        percentage: ((holds.pending / holds.total) * 100).toFixed(1),
      },
      {
        status: "In Transit",
        count: holds.in_transit,
        percentage: ((holds.in_transit / holds.total) * 100).toFixed(1),
      },
      {
        status: "Total",
        count: holds.total,
        percentage: "100.0",
      },
    ];

    await exportData(
      generateExportFilename(`stacksos-holds-org${orgId}`),
      data,
      {
        headers: {
          status: "Hold Status",
          count: "Count",
          percentage: "Percentage (%)",
        },
      }
    );
  }, [holds, orgId, exportData]);

  const handlePrintSummary = useCallback(() => {
    if (!stats || !holds) return;

    printHtml(buildPrintSummaryHtml({ orgId, stats, holds }), {
      title: "StacksOS Daily Summary",
      tone: "report",
    });
  }, [stats, holds, orgId]);

  if (loading) {
    return (
      <PageContainer>
        <PageHeader title="Reports" subtitle="Operational dashboards and exports." breadcrumbs={[{ label: "Reports" }]} />
        <PageContent>
          <LoadingSpinner message="Loading reports…" />
        </PageContent>
      </PageContainer>
    );
  }

  if (error) {
    return (
      <PageContainer>
        <PageHeader title="Reports" subtitle="Operational dashboards and exports." breadcrumbs={[{ label: "Reports" }]} />
        <PageContent>
          <ErrorState error={error} onRetry={loadAll} showHome={false} />
        </PageContent>
      </PageContainer>
    );
  }

  if (!stats || !holds) {
    return (
      <PageContainer>
        <PageHeader title="Reports" subtitle="Operational dashboards and exports." breadcrumbs={[{ label: "Reports" }]} />
        <PageContent>
          <EmptyState title="No data" description="No report data is available yet." />
        </PageContent>
      </PageContainer>
    );
  }

  return (
    <PageContainer>
      <PageHeader
        title="Reports"
        subtitle="Operational dashboards and exports."
        breadcrumbs={[{ label: "Reports" }]}
        actions={[
          { label: "Refresh", onClick: loadAll, icon: RefreshCw },
          {
            label: isExporting ? "Exporting..." : "Download CSV",
            onClick: handleDownloadFullReport,
            icon: isExporting ? Loader2 : Download,
            disabled: isExporting,
          },
          { label: "Print Summary", onClick: handlePrintSummary, icon: Printer },
        ]}
      >
        <div className="flex flex-wrap gap-2">
          <Badge variant="secondary" className="rounded-full">Org {orgId}</Badge>
          <Badge variant="outline" className="rounded-full">Updated {lastRefresh.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</Badge>
          {isExporting && <Badge variant="default" className="rounded-full">Exporting...</Badge>}
        </div>
      </PageHeader>

      <PageContent className="space-y-6">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {statCards.map((card) => (
            <Card key={card.label} className="rounded-2xl border-border/70 shadow-sm">
              <CardContent className="p-5">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-xs uppercase tracking-wide text-muted-foreground">{card.label}</p>
                    <div className="text-2xl font-semibold mt-1">{card.value ?? "—"}</div>
                  </div>
                  <div className={`h-10 w-10 rounded-full flex items-center justify-center ${card.tone}`}>
                    <card.icon className="h-5 w-5" />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Circulation Statistics Card */}
          <Card className="rounded-2xl border-border/70 shadow-sm">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-base flex items-center gap-2">
                    <BarChart3 className="h-4 w-4" /> Circulation Statistics
                  </CardTitle>
                  <CardDescription>Daily circulation metrics for the current org.</CardDescription>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDownloadCirculationStats}
                  disabled={isExporting}
                  className="h-8 gap-2"
                >
                  {isExporting ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <Download className="h-3.5 w-3.5" />
                  )}
                  <span className="sr-only sm:not-sr-only">Export CSV</span>
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">Checkouts Today</div>
                  <div className="text-xl font-semibold">{stats.checkouts_today ?? "—"}</div>
                </div>
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">Checkins Today</div>
                  <div className="text-xl font-semibold">{stats.checkins_today ?? "—"}</div>
                </div>
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">Active Holds</div>
                  <div className="text-xl font-semibold">{stats.active_holds ?? "—"}</div>
                </div>
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">Overdue Items</div>
                  <div className="text-xl font-semibold">{stats.overdue_items ?? "—"}</div>
                </div>
              </div>

              <Separator />

              <div className="grid grid-cols-2 gap-3">
                {stats.fines_collected_today !== null && (
                  <div className="rounded-xl bg-muted/30 p-3">
                    <div className="text-xs text-muted-foreground">Fines Collected</div>
                    <div className="text-xl font-semibold">${(stats.fines_collected_today || 0).toFixed(2)}</div>
                  </div>
                )}
                {stats.new_patrons_today !== null && (
                  <div className="rounded-xl bg-muted/30 p-3">
                    <div className="text-xs text-muted-foreground">New Patrons</div>
                    <div className="text-xl font-semibold">{stats.new_patrons_today ?? "—"}</div>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Holds Statistics Card */}
          <Card className="rounded-2xl border-border/70 shadow-sm">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-base flex items-center gap-2">
                    <Bookmark className="h-4 w-4" /> Holds
                  </CardTitle>
                  <CardDescription>Real-time hold status counts for the current org.</CardDescription>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDownloadHoldsStats}
                  disabled={isExporting}
                  className="h-8 gap-2"
                >
                  {isExporting ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <Download className="h-3.5 w-3.5" />
                  )}
                  <span className="sr-only sm:not-sr-only">Export CSV</span>
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">Ready / Available</div>
                  <div className="text-xl font-semibold">{holds.available}</div>
                  <div className="text-xs text-muted-foreground mt-1">
                    {((holds.available / holds.total) * 100).toFixed(1)}%
                  </div>
                </div>
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">Pending</div>
                  <div className="text-xl font-semibold">{holds.pending}</div>
                  <div className="text-xs text-muted-foreground mt-1">
                    {((holds.pending / holds.total) * 100).toFixed(1)}%
                  </div>
                </div>
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">In transit</div>
                  <div className="text-xl font-semibold">{holds.in_transit}</div>
                  <div className="text-xs text-muted-foreground mt-1">
                    {((holds.in_transit / holds.total) * 100).toFixed(1)}%
                  </div>
                </div>
                <div className="rounded-xl bg-muted/30 p-3">
                  <div className="text-xs text-muted-foreground">Total</div>
                  <div className="text-xl font-semibold">{holds.total}</div>
                  <div className="text-xs text-muted-foreground mt-1">100%</div>
                </div>
              </div>

              <Separator />

              <div className="text-xs text-muted-foreground">
                Note: additional time-series charts (week/month) will be enabled once Evergreen reporting sources are configured.
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Exports Card */}
        <Card className="rounded-2xl border-border/70 shadow-sm">
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Exports & Reports</CardTitle>
            <CardDescription>Download or print operational snapshots in various formats.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              <Button
                variant="outline"
                className="justify-between"
                onClick={handleDownloadFullReport}
                disabled={isExporting}
              >
                Full Report CSV
                {isExporting ? (
                  <Loader2 className="h-4 w-4 text-muted-foreground animate-spin" />
                ) : (
                  <Download className="h-4 w-4 text-muted-foreground" />
                )}
              </Button>
              <Button
                variant="outline"
                className="justify-between"
                onClick={handleDownloadCirculationStats}
                disabled={isExporting}
              >
                Circulation CSV
                {isExporting ? (
                  <Loader2 className="h-4 w-4 text-muted-foreground animate-spin" />
                ) : (
                  <Download className="h-4 w-4 text-muted-foreground" />
                )}
              </Button>
              <Button
                variant="outline"
                className="justify-between"
                onClick={handleDownloadHoldsStats}
                disabled={isExporting}
              >
                Holds CSV
                {isExporting ? (
                  <Loader2 className="h-4 w-4 text-muted-foreground animate-spin" />
                ) : (
                  <Download className="h-4 w-4 text-muted-foreground" />
                )}
              </Button>
            </div>
            <Separator />
            <Button variant="outline" className="w-full justify-between" onClick={handlePrintSummary}>
              Print daily summary
              <Printer className="h-4 w-4 text-muted-foreground" />
            </Button>
            <div className="text-xs text-muted-foreground">
              Scheduled reports will appear here once implemented.
            </div>
          </CardContent>
        </Card>
      </PageContent>
    </PageContainer>
  );
}
